# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:07
from __future__ import unicode_literals

import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da categoria')),
                ('slug', models.SlugField(verbose_name='Atalho')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome e Sobrenome do Editor')),
                ('facebooklink', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do Facebook pessoal')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EnviarEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('texto', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Palavras chaves separadas por vírgula', max_length=150, null=True, verbose_name='Keywords')),
                ('capa', models.ImageField(default='blog/img/logo.svg', help_text='Resolução recomendada: 800x600 horizontal', upload_to=blog.models.path_and_rename, verbose_name='Foto da capa')),
                ('nivel', models.PositiveSmallIntegerField(default=1, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ManyToManyField(to='blog.Categoria')),
                ('editor', models.ManyToManyField(to='blog.Editor')),
            ],
        ),
    ]
