# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('main_image', models.ImageField(upload_to='portifolio/images', verbose_name='Imagem Principal')),
                ('description', models.TextField(blank=True, verbose_name='Descrição ')),
            ],
            options={
                'verbose_name': 'Portfólio',
                'verbose_name_plural': 'Portfólios',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images', verbose_name='Imagem')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição ')),
                ('icon', models.ImageField(upload_to='service/images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('job', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipe',
                'ordering': ['name'],
            },
        ),
    ]
