# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Portifólio',
                'ordering': ['name'],
                'verbose_name_plural': 'Portifólios',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição ')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Serviço',
                'ordering': ['name'],
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('job', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Equipe',
                'ordering': ['name'],
                'verbose_name_plural': 'Equipe',
            },
        ),
    ]
