# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
    ]
