# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_team_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortifolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portifolio/images', verbose_name='Imagem')),
            ],
        ),
        migrations.RemoveField(
            model_name='portifolio',
            name='image',
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição '),
        ),
        migrations.AddField(
            model_name='portifolioimage',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Portifolio'),
        ),
    ]
