# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171111_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='main_image',
            field=models.ImageField(default="{% static'img/logo.png' %}", upload_to='portifolio/images', verbose_name='Imagem'),
        ),
    ]
