# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171008_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolio',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descrição '),
        ),
    ]
