# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171111_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolioimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/images', verbose_name='Imagem'),
        ),
    ]
