# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171112_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portifolio',
            new_name='Portfolio',
        ),
        migrations.RenameModel(
            old_name='PortifolioImage',
            new_name='PortfolioImage',
        ),
    ]
