# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171112_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Nome')),
                ('image', models.ImageField(upload_to='gallery/images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='id_item',
            field=models.CharField(default=1, max_length=3, verbose_name='Insira o id (1, 2, 3,...) do item desejado'),
        ),
    ]
